#!/bin/bash

git pull

(cd fetch-indexes-cpp &&
rm -rf build; mkdir build && (cd build &&
cmake .. && make -j$(nproc)) &&
mv build/fetch-indexes ../ && rm -rf build)

(cd build-packages-cpp &&
rm -rf build; mkdir build && (cd build &&
cmake .. && make -j$(nproc)) &&
mv build/build-packages ../ && rm -rf build)
