packages:
  - name: cmake
    upstream_url: "https://gitlab.kitware.com/cmake/cmake.git"
    upstream_browser: "https://gitlab.kitware.com/cmake/cmake/-/commit/"
    packaging_url: "https://salsa.debian.org/cmake-team/cmake.git"
    packaging_browser: "https://salsa.debian.org/cmake-team/cmake/-/commit/"
    packaging_branch: "master"

releases:
  - plucky
  - oracular
  - noble
