packages:
  - name: qt6-webengine
    upstream_url: "https://code.qt.io/qt/qtwebengine.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtwebengine.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-webengine"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-webengine/commit/?id="
    packaging_branch: "ci/unstable"
    large: true
  - name: qt6-base
    upstream_url: "https://code.qt.io/qt/qtbase.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtbase.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-base"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-base/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-imageformats
    upstream_url: "https://code.qt.io/qt/qtimageformats.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtimageformats.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-imageformats"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-imageformats/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-languageserver
    upstream_url: "https://code.qt.io/qt/qtlanguageserver.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtlanguageserver.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-languageserver"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-languageserver/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-shadertools
    upstream_url: "https://code.qt.io/qt/qtshadertools.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtshadertools.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-shadertools"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-shadertools/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-svg
    upstream_url: "https://code.qt.io/qt/qtsvg.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtsvg.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-svg"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-svg/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-networkauth
    upstream_url: "https://code.qt.io/qt/qtnetworkauth.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtnetworkauth.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-networkauth"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-networkauth/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-serialport
    upstream_url: "https://code.qt.io/qt/qtserialport.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtserialport.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-serialport"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-serialport/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-declarative
    upstream_url: "https://code.qt.io/qt/qtdeclarative.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtdeclarative.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-declarative"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-declarative/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-lottie
    upstream_url: "https://code.qt.io/qt/qtlottie.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtlottie.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-lottie"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-lottie/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-websockets
    upstream_url: "https://code.qt.io/qt/qtwebsockets.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtwebsockets.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-websockets"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-websockets/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-5compat
    upstream_url: "https://code.qt.io/qt/qt5compat.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qt5compat.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-5compat"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-5compat/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-connectivity
    upstream_url: "https://code.qt.io/qt/qtconnectivity.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtconnectivity.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-connectivity"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-connectivity/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-scxml
    upstream_url: "https://code.qt.io/qt/qtscxml.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtscxml.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-scxml"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-scxml/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-sensors
    upstream_url: "https://code.qt.io/qt/qtsensors.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtsensors.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-sensors"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-sensors/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-wayland
    upstream_url: "https://code.qt.io/qt/qtwayland.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtwayland.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-wayland"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-wayland/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-datavis3d
    upstream_url: "https://code.qt.io/qt/qtdatavis3d.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtdatavis3d.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-datavis3d"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-datavis3d/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-grpc
    upstream_url: "https://code.qt.io/qt/qtgrpc.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtgrpc.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-grpc"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-grpc/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-positioning
    upstream_url: "https://code.qt.io/qt/qtpositioning.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtpositioning.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-positioning"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-positioning/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-quicktimeline
    upstream_url: "https://code.qt.io/qt/qtquicktimeline.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtquicktimeline.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-quicktimeline"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-quicktimeline/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-serialbus
    upstream_url: "https://code.qt.io/qt/qtserialbus.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtserialbus.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-serialbus"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-serialbus/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-tools
    upstream_url: "https://code.qt.io/qt/qttools.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qttools.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-tools"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-tools/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-webchannel
    upstream_url: "https://code.qt.io/qt/qtwebchannel.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtwebchannel.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-webchannel"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-webchannel/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-httpserver
    upstream_url: "https://code.qt.io/qt/qthttpserver.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qthttpserver.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-httpserver"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-httpserver/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-remoteobjects
    upstream_url: "https://code.qt.io/qt/qtremoteobjects.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtremoteobjects.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-remoteobjects"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-remoteobjects/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-location
    upstream_url: "https://code.qt.io/qt/qtlocation.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtlocation.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-location"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-location/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-quick3d
    upstream_url: "https://code.qt.io/qt/qtquick3d.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtquick3d.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-quick3d"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-quick3d/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-translations
    upstream_url: "https://code.qt.io/qt/qttranslations.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qttranslations.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-translations"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-translations/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-multimedia
    upstream_url: "https://code.qt.io/qt/qtmultimedia.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtmultimedia.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-multimedia"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-multimedia/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-quick3dphysics
    upstream_url: "https://code.qt.io/qt/qtquick3dphysics.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtquick3dphysics.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-quick3dphysics"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-quick3dphysics/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-graphs
    upstream_url: "https://code.qt.io/qt/qtgraphs.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtgraphs.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-graphs"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-graphs/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-webview
    upstream_url: "https://code.qt.io/qt/qtwebview.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtwebview.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-webview"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-webview/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-speech
    upstream_url: "https://code.qt.io/qt/qtspeech.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtspeech.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-speech"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-speech/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-virtualkeyboard
    upstream_url: "https://code.qt.io/qt/qtvirtualkeyboard.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtvirtualkeyboard.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-virtualkeyboard"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-virtualkeyboard/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-3d
    upstream_url: "https://code.qt.io/qt/qt3d.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qt3d.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-3d"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-3d/commit/?id="
    packaging_branch: "ci/unstable"
  - name: qt6-charts
    upstream_url: "https://code.qt.io/qt/qtcharts.git"
    upstream_browser: "https://code.qt.io/cgit/qt/qtcharts.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-charts"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/qt6-charts/commit/?id="
    packaging_branch: "ci/unstable"
  - name: pyside6
    upstream_url: "https://code.qt.io/pyside/pyside-setup.git"
    upstream_browser: "https://code.qt.io/cgit/pyside/pyside-setup.git/commit/?id="
    packaging_url: "https://git.launchpad.net/~ubuntu-qt-code/+git/pyside6"
    packaging_browser: "https://git.launchpad.net/~ubuntu-qt-code/+git/pyside6/commit/?id="
    packaging_branch: "ci/unstable"

releases:
  - plucky
  - oracular
  - noble
